DROP DATABASE IF EXISTS photographe;
CREATE DATABASE photographe CHARACTER SET 'utf8';

USE photographe;

CREATE TABLE Articles(
  id        SMALLINT      UNSIGNED  PRIMARY KEY AUTO_INCREMENT,
  name      VARCHAR(250)  NOT NULL  UNIQUE,
  text      TEXT          NOT NULL  UNIQUE,
  image     VARCHAR(250)  NOT NULL  UNIQUE,
  alt       VARCHAR(250)  NOT NULL,
  url       VARCHAR(250),
  cat       VARCHAR(25)   NOT NULL,
  createdAt DATETIME      NOT NULL,
  updatedAt DATETIME      NOT NULL)
ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE Images(
  id          SMALLINT      UNSIGNED    PRIMARY KEY  AUTO_INCREMENT,
  url        VARCHAR(250)  NOT NULL    UNIQUE,
  description VARCHAR(250)  NOT NULL,
  gallery     VARCHAR(250)  NOT NULL)
ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE Users(
  id        SMALLINT      UNSIGNED  PRIMARY KEY AUTO_INCREMENT,
  name      VARCHAR(250)  NOT NULL  UNIQUE,
  email     VARCHAR(250)  NOT NULL  UNIQUE,
  image     VARCHAR(250)  NOT NULL  UNIQUE,
  password      VARCHAR(250)  NOT NULL)
ENGINE=INNODB DEFAULT CHARSET=utf8;
